on: [push]
jobs:
  Deploy-HTML:
    runs-on: debian-latest
    steps:
      - name: Print job info
        run: echo "This job was automatically triggered by a ${{ github.event_name }} event. It is now running on a ${{ runner.os }} server hosted by GitHub! The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Check out the commit that triggered this job
        uses: actions/checkout@v4

      - name: Regenerate the HTML
        run: |
          python -m venv venv/
          source venv/bin/activate
          pip install pypandoc
          python abcdune.py -i glossary.tex -d defs.tex -o docs/index.html
